const avgRange = (range) => (range[0] + range[1]) / 2;

export const dietData = {
  // Example user diet (you can adjust these as you wish)
  user_diet: {
    red_meat_g_day: 50,
    poultry_g_day: 60,
    seafood_g_day: 40,
    eggs_g_day: 25,
    milk_g_day: 70,
    cheese_g_day: 20,
    yogurt_g_day: 40,
    cream_g_day: 10,
    butter_g_day: 5,
    whole_fruits_g_day: 300,
    juices_g_day: 50,
    leaves_g_day: 100,
    flowers_g_day: 30,
    red_and_orange_vegetables_g_day: 40,
    starchy_vegetables_g_day: 50,
    stems_g_day: 20,
    other_vegetables_g_day: 30,
    mushrooms_g_day: 10,
    beans_and_lentils_g_day: 40,
    soy_products_g_day: 10,
    nuts_and_seeds_g_day: 10,
    oils_g_day: 30,
    refined_sugar_g_day: 15,
    whole_grains_g_day: 150,
    refined_grains_g_day: 50,
    fiber_g_day: 25,
    fat_pct: 30,
    carbs_pct: 50,
    protein_pct: 20
  },

  // Balanced Omnivore
  balanced_omnivore: {
    red_meat_g_day: avgRange([51, 100]),
    poultry_g_day: avgRange([51, 100]),
    seafood_g_day: avgRange([41, 80]),
    eggs_g_day: avgRange([30, 60]),
    milk_g_day: avgRange([41, 80]),
    cheese_g_day: avgRange([41, 80]),
    yogurt_g_day: avgRange([41, 80]),
    cream_g_day: avgRange([10, 20]),
    butter_g_day: avgRange([10, 20]),
    whole_fruits_g_day: avgRange([211, 422]),
    juices_g_day: avgRange([0, 141]),
    leaves_g_day: avgRange([70, 141]),
    flowers_g_day: avgRange([70, 141]),
    red_and_orange_vegetables_g_day: avgRange([70, 141]),
    starchy_vegetables_g_day: avgRange([70, 141]),
    stems_g_day: avgRange([70, 141]),
    other_vegetables_g_day: avgRange([70, 141]),
    mushrooms_g_day: avgRange([0, 70]),
    beans_and_lentils_g_day: avgRange([60, 121]),
    soy_products_g_day: avgRange([0, 30]),
    nuts_and_seeds_g_day: avgRange([10, 20]),
    oils_g_day: avgRange([28, 56]),
    refined_sugar_g_day: avgRange([0, 35]),
    whole_grains_g_day: avgRange([169, 281]),
    refined_grains_g_day: avgRange([84, 141]),
    fiber_g_day: avgRange([35, 49]),
    fat_pct: avgRange([25, 35]),
    carbs_pct: avgRange([45, 65]),
    protein_pct: avgRange([15, 25])
  },

  // Pescatarian
  pescatarian: {
    red_meat_g_day: avgRange([0, 0]),
    poultry_g_day: avgRange([0, 0]),
    seafood_g_day: avgRange([93, 188]),
    eggs_g_day: avgRange([31, 63]),
    milk_g_day: avgRange([42, 83]),
    cheese_g_day: avgRange([42, 83]),
    yogurt_g_day: avgRange([42, 83]),
    cream_g_day: avgRange([10, 20]),
    butter_g_day: avgRange([10, 20]),
    whole_fruits_g_day: avgRange([218, 437]),
    juices_g_day: avgRange([0, 146]),
    leaves_g_day: avgRange([73, 146]),
    flowers_g_day: avgRange([73, 146]),
    red_and_orange_vegetables_g_day: avgRange([73, 146]),
    starchy_vegetables_g_day: avgRange([73, 146]),
    stems_g_day: avgRange([73, 146]),
    other_vegetables_g_day: avgRange([73, 146]),
    mushrooms_g_day: avgRange([0, 73]),
    beans_and_lentils_g_day: avgRange([93, 156]),
    soy_products_g_day: avgRange([20, 42]),
    nuts_and_seeds_g_day: avgRange([10, 20]),
    oils_g_day: avgRange([29, 58]),
    refined_sugar_g_day: avgRange([0, 36]),
    whole_grains_g_day: avgRange([175, 291]),
    refined_grains_g_day: avgRange([87, 146]),
    fiber_g_day: avgRange([36, 51]),
    fat_pct: avgRange([25, 35]),
    carbs_pct: avgRange([45, 65]),
    protein_pct: avgRange([15, 25])
  },

  // Vegetarian
  vegetarian: {
    red_meat_g_day: avgRange([0, 0]),
    poultry_g_day: avgRange([0, 0]),
    seafood_g_day: avgRange([0, 0]),
    eggs_g_day: avgRange([28, 56]),
    milk_g_day: avgRange([56, 93]),
    cheese_g_day: avgRange([56, 93]),
    yogurt_g_day: avgRange([56, 93]),
    cream_g_day: avgRange([14, 24]),
    butter_g_day: avgRange([14, 24]),
    whole_fruits_g_day: avgRange([328, 524]),
    juices_g_day: avgRange([0, 131]),
    leaves_g_day: avgRange([98, 164]),
    flowers_g_day: avgRange([98, 164]),
    red_and_orange_vegetables_g_day: avgRange([98, 164]),
    starchy_vegetables_g_day: avgRange([98, 164]),
    stems_g_day: avgRange([66, 131]),
    other_vegetables_g_day: avgRange([66, 131]),
    mushrooms_g_day: avgRange([0, 66]),
    beans_and_lentils_g_day: avgRange([75, 113]),
    soy_products_g_day: avgRange([38, 56]),
    nuts_and_seeds_g_day: avgRange([18, 38]),
    oils_g_day: avgRange([26, 52]),
    refined_sugar_g_day: avgRange([0, 33]),
    whole_grains_g_day: avgRange([197, 328]),
    refined_grains_g_day: avgRange([79, 105]),
    fiber_g_day: avgRange([33, 46]),
    fat_pct: avgRange([25, 35]),
    carbs_pct: avgRange([50, 60]),
    protein_pct: avgRange([15, 25])
  },

  // Vegan
  vegan: {
    red_meat_g_day: avgRange([0, 0]),
    poultry_g_day: avgRange([0, 0]),
    seafood_g_day: avgRange([0, 0]),
    eggs_g_day: avgRange([0, 0]),
    milk_g_day: avgRange([0, 0]),
    cheese_g_day: avgRange([0, 0]),
    yogurt_g_day: avgRange([0, 0]),
    cream_g_day: avgRange([0, 0]),
    butter_g_day: avgRange([0, 0]),
    whole_fruits_g_day: avgRange([335, 559]),
    juices_g_day: avgRange([0, 112]),
    leaves_g_day: avgRange([112, 168]),
    flowers_g_day: avgRange([112, 168]),
    red_and_orange_vegetables_g_day: avgRange([112, 168]),
    starchy_vegetables_g_day: avgRange([112, 168]),
    stems_g_day: avgRange([56, 112]),
    other_vegetables_g_day: avgRange([56, 112]),
    mushrooms_g_day: avgRange([0, 56]),
    beans_and_lentils_g_day: avgRange([144, 224]),
    soy_products_g_day: avgRange([48, 79]),
    nuts_and_seeds_g_day: avgRange([16, 32]),
    oils_g_day: avgRange([22, 45]),
    refined_sugar_g_day: avgRange([0, 28]),
    whole_grains_g_day: avgRange([268, 402]),
    refined_grains_g_day: avgRange([67, 67]), // same min-max
    fiber_g_day: avgRange([34, 45]),
    fat_pct: avgRange([20, 30]),
    carbs_pct: avgRange([55, 65]),
    protein_pct: avgRange([10, 20])
  },

  // Paleo
  paleo: {
    red_meat_g_day: avgRange([143, 288]),
    poultry_g_day: avgRange([109, 215]),
    seafood_g_day: avgRange([87, 173]),
    eggs_g_day: avgRange([58, 115]),
    milk_g_day: avgRange([0, 0]),
    cheese_g_day: avgRange([0, 0]),
    yogurt_g_day: avgRange([0, 0]),
    cream_g_day: avgRange([0, 0]),
    butter_g_day: avgRange([0, 0]),
    whole_fruits_g_day: avgRange([402, 805]),
    juices_g_day: avgRange([0, 0]),
    leaves_g_day: avgRange([201, 302]),
    flowers_g_day: avgRange([201, 302]),
    red_and_orange_vegetables_g_day: avgRange([201, 302]),
    starchy_vegetables_g_day: avgRange([201, 302]),
    stems_g_day: avgRange([101, 201]),
    other_vegetables_g_day: avgRange([101, 201]),
    mushrooms_g_day: avgRange([0, 101]),
    beans_and_lentils_g_day: avgRange([0, 0]),
    soy_products_g_day: avgRange([0, 0]),
    nuts_and_seeds_g_day: avgRange([28, 58]),
    oils_g_day: avgRange([60, 101]),
    refined_sugar_g_day: avgRange([0, 0]),
    whole_grains_g_day: avgRange([0, 0]),
    refined_grains_g_day: avgRange([0, 0]),
    fiber_g_day: avgRange([40, 60]),
    fat_pct: avgRange([30, 50]),
    carbs_pct: avgRange([20, 40]),
    protein_pct: avgRange([20, 35])
  },

  // Keto
  keto: {
    red_meat_g_day: avgRange([206, 345]),
    poultry_g_day: avgRange([137, 206]),
    seafood_g_day: avgRange([123, 206]),
    eggs_g_day: avgRange([96, 137]),
    milk_g_day: avgRange([56, 110]),
    cheese_g_day: avgRange([83, 166]),
    yogurt_g_day: avgRange([0, 56]),
    cream_g_day: avgRange([27, 56]),
    butter_g_day: avgRange([27, 56]),
    whole_fruits_g_day: avgRange([0, 96]),
    juices_g_day: avgRange([0, 0]),
    leaves_g_day: avgRange([96, 193]),
    flowers_g_day: avgRange([96, 193]),
    red_and_orange_vegetables_g_day: avgRange([48, 144]),
    starchy_vegetables_g_day: avgRange([0, 48]),
    stems_g_day: avgRange([48, 144]),
    other_vegetables_g_day: avgRange([48, 144]),
    mushrooms_g_day: avgRange([0, 96]),
    beans_and_lentils_g_day: avgRange([0, 0]),
    soy_products_g_day: avgRange([0, 56]),
    nuts_and_seeds_g_day: avgRange([27, 83]),
    oils_g_day: avgRange([77, 116]),
    refined_sugar_g_day: avgRange([0, 0]),
    whole_grains_g_day: avgRange([0, 0]),
    refined_grains_g_day: avgRange([0, 0]),
    fiber_g_day: avgRange([29, 48]),
    fat_pct: avgRange([70, 80]),
    carbs_pct: avgRange([5, 10]),
    protein_pct: avgRange([20, 25])
  },

  // Carnivore
  carnivore: {
    red_meat_g_day: avgRange([1040, 1733]),
    poultry_g_day: avgRange([0, 347]),
    seafood_g_day: avgRange([0, 347]),
    eggs_g_day: avgRange([0, 246]),
    milk_g_day: avgRange([0, 347]),
    cheese_g_day: avgRange([0, 347]),
    yogurt_g_day: avgRange([0, 347]),
    cream_g_day: avgRange([0, 347]),
    butter_g_day: avgRange([0, 347]),
    whole_fruits_g_day: avgRange([0, 0]),
    juices_g_day: avgRange([0, 0]),
    leaves_g_day: avgRange([0, 0]),
    flowers_g_day: avgRange([0, 0]),
    red_and_orange_vegetables_g_day: avgRange([0, 0]),
    starchy_vegetables_g_day: avgRange([0, 0]),
    stems_g_day: avgRange([0, 0]),
    other_vegetables_g_day: avgRange([0, 0]),
    mushrooms_g_day: avgRange([0, 0]),
    beans_and_lentils_g_day: avgRange([0, 0]),
    soy_products_g_day: avgRange([0, 0]),
    nuts_and_seeds_g_day: avgRange([0, 0]),
    oils_g_day: avgRange([0, 0]),
    refined_sugar_g_day: avgRange([0, 0]),
    whole_grains_g_day: avgRange([0, 0]),
    refined_grains_g_day: avgRange([0, 0]),
    fiber_g_day: avgRange([0, 0]),
    fat_pct: avgRange([55, 75]),
    carbs_pct: avgRange([0, 5]),
    protein_pct: avgRange([25, 45])
  }
};